### ISSUE TITLE
Missing Functions GRIDobj

### ISSUE THREAD

**Issue by AgoLudo** [wschwanghart/topotoolbox#26]

**Comment by wschwanghart** [comment]
Dear @AgoLudo,
I guess the issue was resolved. You'll need the image processing toolbox to run TT (and Cascade).
Cheers, Wolfgang

**Comment by AgoLudo** [comment]
Dear @wschwanghart that's what I realised shortly after I posted, I am still not very familiar with the Image and Map processing toolbox in matlab. Anyway, thank you very much for the quick reply
Best regards, LudoAgo
